package basicjava;

public class excep2 {
	public static void main(String args[])
	{
		int a=10,b=0;
		int c[]=new int[5];
		try {
	
			System.out.println(a/b);
			}
		catch(ArithmeticException ae)
		{
			System.out.println(ae);
		}
		catch(Exception ae)
		{
			System.out.println(ae);
		}
		System.out.println("after exception");
	}

}
